spring:
  output:
    ansi:
      enabled: detect
  banner:
    location: config/banner.txt
  data:
    rest:
      base-path: /rest
      detection-strategy: all
      default-media-type: application/json
      max-page-size: 50
  jackson:
    date-format: "yyyy-MM-dd"
    serialization:
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_SELF_REFERENCES: false
    default-property-inclusion: always
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DATASOURCE-POOL
  session:
    store-type: jdbc
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: kr.sungha.boot.jpa.PrefixNamingStrategy
    properties:
      javax:
        persistence:
          validation:
            mode: none
  security:
    oauth2:
      client:
        registration:
          github:
          facebook:
          twitter:
          google:
            scope: profile,email
          kakao:
            client-name: Kakao
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
          naver:
            client-name: Naver
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile
          apple:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/toke
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  pattern:
    console: "%clr(%d{MM/dd HH:mm:ss.SSS}){green} %clr(%5p){blue} %m %clr(\\(%C{0}.java:%line\\)){cyan}%n"
  group:
    application:
      - kr.sungha
  level:
    root: INFO
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
#          - info
#          - health
#          - logfile
#          - env
#          - configprops




