name: build

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2
    - name: Build with Maven
      run: mvn package -B -V -e "-Dstyle.color=always"
      env:
        MAVEN_OPTS: -Djansi.force=true
